Repository OWASP/DevGuide, pull requests merged in 2025-05, with the labels that each got.

#91 apply checks before deploying web doc
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
  .spellcheck-en.yaml
  .wordlist-en.txt
  README.md
  release-process.md
Labels: automation

#94 revise links and wording for SKF pages
  docs/03-requirements/07-skf.md
  docs/07-training-education/03-skf.md
  mkdocs.yaml
Labels: bug, 4.1.9

#95 Fix link issues
  docs/09-operations/01-devsecops.md
Labels: bug, 4.1.9

#98 Create PDFs as separate task
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
  .gitignore
  docs/en/04-design/index.md
  docs/es/04-design/02-web-app-checklist/02-frameworks-libraries.md
  docs/es/04-design/index.md
  docs/es/06-verification/02-tools/index.md
  docs/es/06-verification/03-frameworks/index.md
  mkdocs-pdf-en.yaml
  mkdocs-pdf-es.yaml
  mkdocs.yaml
Labels: automation, 4.1.9

#99 Provide new tab for contributors
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
  .gitignore
  .wordlist-en.txt
  contributing.md
  mkdocs.yaml
Labels: enhancement, 4.1.9

#103 Migrate content for PT-BR translation
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
  .gitignore
  .spellcheck-pt-br.yaml
  .wordlist-en.txt
  .wordlist-pt-br.txt
  contributing.md
  docs/pt-br/02-foundations/01-security-fundamentals.md
  docs/pt-br/02-foundations/05-top-ten.md
  docs/pt-br/02-foundations/index.md
  docs/pt-br/index.md
  mkdocs-pdf-pt-br.yaml
  mkdocs.yaml
Labels: automation, 4.1.9
